"use client"
import { useState } from "react"
import { Copy, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog"
import type { Protocol, Affordance, Domain } from "@/lib/protocol-data"

interface PromptExportDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  selectedProtocols: Protocol[]
  selectedDomain?: Domain
  selectedAffordances?: Affordance[]
}

export function PromptExportDialog({
  open,
  onOpenChange,
  selectedProtocols,
  selectedDomain,
  selectedAffordances,
}: PromptExportDialogProps) {
  const [copied, setCopied] = useState(false)

  const generatePrompt = () => {
    let prompt = `# Open Protocol Stack Context\n`
    prompt += `# Generated by OpenHaven — openhaven.net\n\n`

    if (selectedDomain) {
      prompt += `## Use Case\n${selectedDomain.name}: ${selectedDomain.description}\n\n`
    }

    if (selectedAffordances?.length) {
      prompt += `## Required Affordances\n`
      selectedAffordances.forEach((a) => {
        prompt += `- **${a.name}**: ${a.description}\n`
      })
      prompt += "\n"
    }

    prompt += `## Selected Protocols\n\n`
    selectedProtocols.forEach((p) => {
      prompt += `### ${p.name}\n`
      prompt += `**Type:** ${p.entityType} | **Architecture:** ${p.architectureType} | **Governance:** ${p.governanceModel}\n`
      prompt += `**Capture Risk:** ${p.captureRisk} | **License:** ${p.sourceLicense} | **Self-hostable:** ${p.selfHostable ? "Yes" : "No"}\n`
      prompt += `**Summary:** ${p.summary}\n`
      if (p.verifiedAffordanceIds.length) {
        prompt += `**Verified capabilities:** ${p.verifiedAffordanceIds.join(", ")}\n`
      }
      if (p.claimedAffordanceIds.length) {
        prompt += `**Claimed (unverified):** ${p.claimedAffordanceIds.join(", ")}\n`
      }
      if (p.docLink) prompt += `**Documentation:** ${p.docLink}\n`
      prompt += "\n"
    })

    prompt += `## Implementation Notes\n`
    prompt += `- Respect data sovereignty: users control their own data\n`
    prompt += `- Implement offline-first capabilities where applicable\n`
    prompt += `- Prefer self-hosted deployment over managed services\n`
    prompt += `- All capability claims above are ${
      selectedProtocols.some((p) => p.isDraft)
        ? "draft/beta — verify against current documentation"
        : "verified"
    }\n`

    return prompt
  }

  const copy = async () => {
    await navigator.clipboard.writeText(generatePrompt())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[80vh] max-w-2xl overflow-hidden">
        <DialogHeader>
          <DialogTitle>Your Protocol Stack Context</DialogTitle>
          <DialogDescription>
            Paste into Cursor, Claude Code, Windsurf, or any AI IDE to get protocol-aware
            implementation help.
          </DialogDescription>
        </DialogHeader>
        <div className="relative max-h-[45vh] overflow-auto rounded-lg border border-border bg-muted p-4">
          <pre className="whitespace-pre-wrap font-mono text-xs text-foreground">
            {generatePrompt()}
          </pre>
        </div>
        <Button className="w-full gap-2" onClick={copy}>
          {copied ? (
            <>
              <Check className="h-4 w-4" /> Copied!
            </>
          ) : (
            <>
              <Copy className="h-4 w-4" /> Copy to Clipboard
            </>
          )}
        </Button>
        <p className="text-center text-xs text-muted-foreground">
          For full landscape context, use{" "}
          <a href="/llms-full.txt" className="text-primary underline-offset-4 hover:underline">
            /llms-full.txt
          </a>
        </p>
      </DialogContent>
    </Dialog>
  )
}
