"use client"

import { useState } from "react"
import { Copy, Check, Sparkles, Code2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { protocols } from "@/lib/protocol-data"

const recommendedProtocols = protocols.filter((p) => p.status === "recommended")

export function ExportSection() {
  const [selectedProtocols, setSelectedProtocols] = useState<string[]>([])
  const [showExport, setShowExport] = useState(false)
  const [copied, setCopied] = useState(false)

  const toggleProtocol = (id: string) => {
    setSelectedProtocols((prev) =>
      prev.includes(id) ? prev.filter((p) => p !== id) : [...prev, id]
    )
  }

  const selectAll = () => {
    setSelectedProtocols(recommendedProtocols.map((p) => p.id))
  }

  const clearAll = () => {
    setSelectedProtocols([])
  }

  const generatePrompt = () => {
    const selected = recommendedProtocols.filter((p) =>
      selectedProtocols.includes(p.id)
    )

    let prompt = `# Tech Stack Context for AI Assistant

## Selected Open Protocols

The following protocols have been selected for this project based on community evaluations from the Open Protocol Navigator (in partnership with the Collaborative Technology Alliance).

`

    for (const protocol of selected) {
      prompt += `### ${protocol.name}
**Use Case:** ${protocol.useCase}
**Why This Choice:** ${protocol.rationale.replace("[Demo content] ", "")}
**Key Concepts:** ${protocol.category}
${protocol.docLink ? `**Documentation:** ${protocol.docLink}` : ""}

`
    }

    prompt += `---

## Implementation Notes

Please ensure interoperability between these layers where possible. When implementing features:
1. Respect the data sovereignty principles these protocols embody
2. Implement proper error handling for decentralized network operations
3. Consider offline-first capabilities where applicable
4. Follow each protocol's security best practices

Generated by Open Protocol Navigator | openprotocolnavigator.org`

    return prompt
  }

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(generatePrompt())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <section id="export" className="bg-card px-4 py-20 sm:py-28">
      <div className="mx-auto max-w-4xl">
        <div className="mb-12 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-background px-4 py-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <span className="text-sm font-medium text-foreground">
              Vibe Coding Ready
            </span>
          </div>
          <h2 className="mb-4 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Export Your Stack for AI-Assisted Development
          </h2>
          <p className="mx-auto max-w-2xl text-muted-foreground">
            Select your protocols and generate context for Cursor, Windsurf,
            Claude, or your vibe coding tool of choice.
          </p>
        </div>

        <div className="overflow-hidden rounded-xl border border-border bg-background">
          <div className="flex items-center justify-between border-b border-border bg-muted/50 px-6 py-4">
            <h3 className="font-semibold text-foreground">
              Select Protocols ({selectedProtocols.length} selected)
            </h3>
            <div className="flex gap-2">
              <Button variant="ghost" size="sm" onClick={selectAll}>
                Select All
              </Button>
              <Button variant="ghost" size="sm" onClick={clearAll}>
                Clear
              </Button>
            </div>
          </div>

          <div className="grid gap-1 p-4 sm:grid-cols-2">
            {recommendedProtocols.map((protocol) => (
              <label
                key={protocol.id}
                className="flex cursor-pointer items-start gap-3 rounded-lg p-3 transition-colors hover:bg-muted/50"
              >
                <Checkbox
                  id={protocol.id}
                  checked={selectedProtocols.includes(protocol.id)}
                  onCheckedChange={() => toggleProtocol(protocol.id)}
                  className="mt-0.5"
                />
                <div className="flex-1">
                  <span className="font-medium text-foreground">
                    {protocol.name}
                  </span>
                  <p className="text-xs text-muted-foreground">
                    {protocol.useCase}
                  </p>
                </div>
              </label>
            ))}
          </div>

          <div className="border-t border-border bg-muted/50 px-6 py-4">
            <Button
              className="w-full gap-2 sm:w-auto"
              disabled={selectedProtocols.length === 0}
              onClick={() => setShowExport(true)}
            >
              <Code2 className="h-4 w-4" />
              Generate Prompt
            </Button>
          </div>
        </div>

        <Dialog open={showExport} onOpenChange={setShowExport}>
          <DialogContent className="max-h-[80vh] max-w-2xl overflow-hidden">
            <DialogHeader>
              <DialogTitle>Your Protocol Context Prompt</DialogTitle>
              <DialogDescription>
                Paste this into your AI IDE or coding assistant to provide
                protocol context for implementation help.
              </DialogDescription>
            </DialogHeader>

            <div className="relative max-h-[50vh] overflow-auto rounded-lg border border-border bg-muted p-4">
              <pre className="whitespace-pre-wrap font-mono text-xs text-foreground">
                {generatePrompt()}
              </pre>
            </div>

            <Button className="w-full gap-2" onClick={copyToClipboard}>
              {copied ? (
                <>
                  <Check className="h-4 w-4" />
                  Copied to Clipboard!
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4" />
                  Copy to Clipboard
                </>
              )}
            </Button>
          </DialogContent>
        </Dialog>
      </div>
    </section>
  )
}
